# Generated by Django 5.1.15 on 2026-07-26 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID. Safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        db_index=True,
                        help_text="Primary login identifier. Stored in normalized format: +91XXXXXXXXXX.",
                        max_length=15,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional email. Can be used for notifications and future email login.",
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="User's display name.", max_length=150),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("guest", "Guest"),
                            ("lender", "Lender"),
                            ("employee", "Employee"),
                            ("admin", "Admin"),
                        ],
                        db_index=True,
                        default="guest",
                        help_text="Determines the user's platform role and capabilities.",
                        max_length=20,
                    ),
                ),
                (
                    "is_mobile_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True after successful OTP verification.",
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True after email link verification.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Inactive users cannot authenticate."
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Grants access to Django admin interface.",
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last API activity.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "login_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the login attempt occurred."
                    ),
                ),
                (
                    "logout_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user logged out (null if still active).",
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Client IP address.", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="Browser/app User-Agent string."
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. mobile, tablet, desktop.",
                        max_length=50,
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, help_text="Detected browser name.", max_length=100
                    ),
                ),
                (
                    "operating_system",
                    models.CharField(
                        blank=True,
                        help_text="Detected operating system.",
                        max_length=100,
                    ),
                ),
                (
                    "login_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                        ],
                        default="success",
                        help_text="Outcome of the login attempt.",
                        max_length=20,
                    ),
                ),
                (
                    "failure_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why authentication failed (if applicable).",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who attempted authentication.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Login History",
                "verbose_name_plural": "Login Histories",
                "ordering": ["-login_at"],
            },
        ),
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        db_index=True,
                        help_text="The mobile number this OTP was issued to.",
                        max_length=15,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("forgot_password", "Forgot Password"),
                            ("mobile_change", "Mobile Number Change"),
                            ("login", "Login"),
                            ("account_verification", "Account Verification"),
                        ],
                        help_text="What this OTP is used for.",
                        max_length=30,
                    ),
                ),
                (
                    "otp_hash",
                    models.CharField(
                        help_text="SHA-256 hash of the OTP combined with a secret salt. Never plain text.",
                        max_length=64,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="OTP becomes invalid after this timestamp."
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of failed verification attempts so far.",
                    ),
                ),
                (
                    "max_attempts",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum allowed verification attempts."
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True after successful verification.",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the OTP was successfully verified.",
                        null=True,
                    ),
                ),
                (
                    "is_invalidated",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True when superseded by a newer OTP for the same purpose.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated user (nullable for pre-registration OTPs).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP Verification",
                "verbose_name_plural": "OTP Verifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("TERMS_OF_SERVICE", "Terms of Service"),
                            ("PRIVACY_POLICY", "Privacy Policy"),
                            ("COMMUNICATION_OPT_IN", "Communication Opt-In"),
                            ("BORROWER_LOAN_AGREEMENT", "Borrower Loan Agreement"),
                        ],
                        help_text="What was consented to.",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Policy version, e.g. 'v1.0'.", max_length=20
                    ),
                ),
                (
                    "is_agreed",
                    models.BooleanField(
                        default=True, help_text="Whether the user agreed."
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Client IP when consent was given.",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="Browser/app User-Agent when consent was given.",
                    ),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When consent was captured."
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context about consent event.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who gave consent.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Consent",
                "verbose_name_plural": "User Consents",
                "ordering": ["-accepted_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "refresh_token_jti",
                    models.CharField(
                        db_index=True,
                        help_text="JWT ID (jti) claim from the refresh token. Used for session revocation.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Chrome — Windows, Android — Samsung Galaxy.",
                        max_length=200,
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. mobile, tablet, desktop.",
                        max_length=50,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated on every authenticated API request.",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the refresh token expires."),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Set to False on logout or token revocation.",
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this session was explicitly revoked.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The authenticated user.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["mobile_number"], name="accounts_us_mobile__bd5794_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["public_id"], name="accounts_us_public__a83b1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["account_type"], name="accounts_us_account_28efcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "login_at"], name="accounts_lo_user_id_64847b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["login_status"], name="accounts_lo_login_s_6d7edd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["mobile_number", "purpose"],
                name="accounts_ot_mobile__a6b283_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="otpverification",
            index=models.Index(
                fields=["expires_at"], name="accounts_ot_expires_b7415d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(
                fields=["user", "consent_type", "version"],
                name="accounts_us_user_id_e36fda_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userconsent",
            index=models.Index(
                fields=["accepted_at"], name="accounts_us_accepte_17568f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "is_active"], name="accounts_us_user_id_91ed82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["refresh_token_jti"], name="accounts_us_refresh_61d6c4_idx"
            ),
        ),
    ]
