# Generated by Django 5.1.15 on 2026-07-27 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("mobile_number", models.CharField(max_length=20)),
                (
                    "business_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact Inquiry",
                "verbose_name_plural": "Contact Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="accounts_lo_user_id_64847b_idx",
        ),
        migrations.RemoveIndex(
            model_name="loginhistory",
            name="accounts_lo_login_s_6d7edd_idx",
        ),
        migrations.RemoveIndex(
            model_name="otpverification",
            name="accounts_ot_mobile__a6b283_idx",
        ),
        migrations.RemoveIndex(
            model_name="otpverification",
            name="accounts_ot_expires_b7415d_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_mobile__bd5794_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_public__a83b1e_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_account_28efcc_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="accounts_us_is_acti_a5841d_idx",
        ),
        migrations.RemoveIndex(
            model_name="userconsent",
            name="accounts_us_user_id_e36fda_idx",
        ),
        migrations.RemoveIndex(
            model_name="userconsent",
            name="accounts_us_accepte_17568f_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersession",
            name="accounts_us_user_id_91ed82_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersession",
            name="accounts_us_refresh_61d6c4_idx",
        ),
        migrations.RemoveField(
            model_name="otpverification",
            name="is_invalidated",
        ),
        migrations.RemoveField(
            model_name="otpverification",
            name="verified_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_activity_at",
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="browser",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="failure_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="login_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="login_status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("blocked", "Blocked"),
                ],
                default="success",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="logout_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="operating_system",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="login_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="loginhistory",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="max_attempts",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="mobile_number",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="otp_hash",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("registration", "Registration"),
                    ("login", "Login"),
                    ("password_reset", "Password Reset"),
                    ("account_verification", "Account Verification"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otps",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="accepted_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("terms_of_service", "Terms of Service"),
                    ("privacy_policy", "Privacy Policy"),
                    ("credit_report_auth", "Credit Report Authorization"),
                    ("data_processing", "Data Processing Consent"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="is_agreed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="version",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="device_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="device_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="expires_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="last_activity_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="refresh_token_jti",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
