# Generated by Django 5.1.15 on 2026-08-01 00:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("masters", "0002_customerreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created."
            ),
        ),
        migrations.AlterField(
            model_name="customerreview",
            name="public_id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text="External-facing UUID identifier, safe to expose in APIs.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customerreview",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when this record was last modified."
            ),
        ),
    ]
