# Generated by Django 5.1.15 on 2026-07-26 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID identifier, safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                (
                    "customer_code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated unique identifier, e.g. FR0010042.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("mobile_number", models.CharField(max_length=15)),
                ("alternate_mobile", models.CharField(blank=True, max_length=15)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="customer_photos/"
                    ),
                ),
                ("id_proof_type", models.CharField(blank=True, max_length=50)),
                ("id_proof_number", models.CharField(blank=True, max_length=50)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pin_code", models.CharField(blank=True, max_length=10)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Interest rate as a decimal, e.g. 2.5 for 2.5%.",
                        max_digits=8,
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Original principal amount.",
                        max_digits=12,
                    ),
                ),
                (
                    "disbursed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual amount handed to the customer.",
                        max_digits=12,
                    ),
                ),
                (
                    "total_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total repayable amount (principal + interest). Auto-calculated on save.",
                        max_digits=12,
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=0,
                        help_text="Remaining amount to be collected. Updated by CollectionService.",
                        max_digits=12,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("defaulted", "Defaulted"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Customer Profile",
                "verbose_name_plural": "Customer Profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID identifier, safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expense_date", models.DateField(db_index=True)),
                ("description", models.TextField(blank=True)),
                (
                    "receipt_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="expense_receipts/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestWorkspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID identifier, safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Business name, e.g. 'Ramesh Finance'.",
                        max_length=200,
                    ),
                ),
                (
                    "mobile_number",
                    models.CharField(
                        help_text="Business contact number.", max_length=15
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="workspace_logos/"
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pin_code", models.CharField(blank=True, max_length=10)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[("free", "Free"), ("premium", "Premium")],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("read_only", "Read Only"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "max_customers_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If set, overrides the plan's default customer limit for this workspace.",
                        null=True,
                    ),
                ),
                (
                    "max_collection_days_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If set, overrides the plan's default weekly collection day limit.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Guest Workspace",
                "verbose_name_plural": "Guest Workspaces",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollectionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID identifier, safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                (
                    "collection_date",
                    models.DateField(
                        db_index=True,
                        help_text="The date the collection was recorded for.",
                    ),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What was scheduled to be collected.",
                        max_digits=12,
                    ),
                ),
                (
                    "collected_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What was actually collected.",
                        max_digits=12,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                (
                    "receipt_number",
                    models.CharField(
                        help_text="Auto-generated receipt number.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "gps_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Entry",
                "verbose_name_plural": "Collection Entries",
                "ordering": ["-collection_date", "-created_at"],
            },
        ),
    ]
