# Generated by Django 5.1.15 on 2026-07-26 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("guest_workspace", "0001_initial"),
        ("masters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionentry",
            name="payment_mode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_entries",
                to="masters.paymentmode",
            ),
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="collection_entries",
                to="masters.collectionstatus",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="collection_frequency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="masters.collectionfrequency",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_customers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="interest_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers",
                to="masters.interesttype",
            ),
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="guest_workspace.customerprofile",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="masters.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_mode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="masters.paymentmode",
            ),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="business_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Type of finance business.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="masters.businesscategory",
            ),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="owner",
            field=models.OneToOneField(
                help_text="The user who owns and manages this workspace.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guest_workspace",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expenses",
                to="guest_workspace.guestworkspace",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="guest_workspace.guestworkspace",
            ),
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="guest_workspace.guestworkspace",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["workspace", "expense_date"],
                name="guest_works_workspa_aa547c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["workspace", "category"], name="guest_works_workspa_f9d88d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["workspace", "status"], name="guest_works_workspa_7b6bb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["workspace", "customer_code"],
                name="guest_works_workspa_a3d5cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["mobile_number"], name="guest_works_mobile__29d62e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentry",
            index=models.Index(
                fields=["workspace", "collection_date"],
                name="guest_works_workspa_2f1be0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentry",
            index=models.Index(
                fields=["customer", "collection_date"],
                name="guest_works_custome_6db1f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collectionentry",
            index=models.Index(
                fields=["workspace", "status"], name="guest_works_workspa_376b08_idx"
            ),
        ),
    ]
