# Generated by Django on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="is_existing_borrower",
            field=models.BooleanField(
                default=False,
                help_text="Flag indicating if the customer was imported as an ongoing loan with prior payments.",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="total_installments",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Total number of planned collection installments for this loan.",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="installments_paid_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of installments already collected before or during workspace creation.",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="remaining_installments_count",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of installments remaining to be collected.",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="amount_already_collected",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                help_text="Amount already collected prior to workspace creation.",
            ),
        ),
    ]
