# Generated by Django 5.1.15 on 2026-07-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0003_customerprofile_installment_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guestworkspace",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("guest", "Guest Free"),
                    ("free", "Free"),
                    ("starter", "ERP Starter"),
                    ("premium", "Premium"),
                    ("enterprise", "Enterprise"),
                ],
                db_index=True,
                default="free",
                max_length=20,
            ),
        ),
    ]
