# Generated by Django on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0004_alter_guestworkspace_subscription_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="collection_day",
            field=models.CharField(
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                db_index=True,
                default="monday",
                help_text="Assigned day of the week for weekly/scheduled collections.",
                max_length=20,
            ),
        ),
    ]
