# Generated by Django on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0005_customerprofile_collection_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestworkspace",
            name="allowed_collection_days",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Configured collection days of week for this workspace e.g. ['wednesday'].",
            ),
        ),
    ]
