# Generated by Django 5.1.15 on 2026-07-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0006_guestworkspace_allowed_collection_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="installment_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Custom per-installment collection amount for this borrower.",
                max_digits=12,
            ),
        ),
    ]
