# Generated by Django 5.1.15 on 2026-07-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0008_customerprofile_sequence_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionentry",
            name="is_collected_today",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="True if collected today, False if past/backdated collection.",
            ),
        ),
    ]
