# Generated by Django 5.1.15 on 2026-07-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0009_collectionentry_is_collected_today"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestworkspace",
            name="purchased_additional_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of additional collection days purchased by the guest user.",
            ),
        ),
    ]
