# Generated by Django 5.1.15 on 2026-08-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0010_guestworkspace_purchased_additional_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestworkspace",
            name="alternate_mobile",
            field=models.CharField(
                blank=True, help_text="Secondary contact phone number", max_length=15
            ),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="business_type",
            field=models.CharField(
                blank=True, help_text="Business type e.g. Daily Finance", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="gstin",
            field=models.CharField(
                blank=True, help_text="GSTIN Tax Identification Number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="pan_number",
            field=models.CharField(
                blank=True, help_text="Owner/Business PAN Number", max_length=15
            ),
        ),
    ]
