# Generated by Django 5.1.15 on 2026-08-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0011_guestworkspace_alternate_mobile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guestworkspace",
            name="alternate_mobile",
        ),
        migrations.RemoveField(
            model_name="guestworkspace",
            name="business_type",
        ),
        migrations.RemoveField(
            model_name="guestworkspace",
            name="gstin",
        ),
        migrations.RemoveField(
            model_name="guestworkspace",
            name="pan_number",
        ),
    ]
