# Generated by Django 5.1.15 on 2026-08-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0012_remove_guestworkspace_alternate_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestworkspace",
            name="business_type",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="gstin",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="owner_pan",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
    ]
