# Generated by Django 5.1.15 on 2026-08-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "guest_workspace",
            "0013_guestworkspace_business_type_guestworkspace_gstin_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionentry",
            name="edit_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of times this collection entry was edited (Max allowed: 1).",
            ),
        ),
        migrations.AddField(
            model_name="collectionentry",
            name="is_edited",
            field=models.BooleanField(
                default=False,
                help_text="True if this collection entry record/date was edited once.",
            ),
        ),
    ]
