# Generated by Django 5.1.15 on 2026-08-05 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "guest_workspace",
            "0014_collectionentry_edit_count_collectionentry_is_edited",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID identifier, safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        db_index=True,
                        help_text="The date this starting cash/capital was injected for.",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of capital/cash added.",
                        max_digits=12,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Optional description e.g. Starting cash brought from home/bank.",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="capital_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_entries",
                        to="guest_workspace.guestworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capital Entry",
                "verbose_name_plural": "Capital Entries",
                "ordering": ["-entry_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "entry_date"],
                        name="guest_works_workspa_ad0318_idx",
                    )
                ],
            },
        ),
    ]
