# Generated by Django 5.1.15 on 2026-08-08 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0015_capitalentry"),
        ("masters", "0003_alter_customerreview_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customerprofile",
            index=models.Index(
                fields=["workspace", "start_date"],
                name="guest_works_workspa_7bd97c_idx",
            ),
        ),
    ]
