# Generated by Django 5.1.15 on 2026-08-08 16:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0016_customerprofile_guest_works_workspa_7bd97c_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID identifier, safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the line/route e.g. Line 1 - Market Area.",
                        max_length=150,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        help_text="Area or locality details e.g. Market Road, Sector 4.",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="guest_workspace.guestworkspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Line",
                "verbose_name_plural": "Collection Lines",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="LineDaySchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when this record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this record was last modified.",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="External-facing UUID identifier, safe to expose in APIs.",
                        unique=True,
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "portion",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (1:00 AM – 1:00 PM)"),
                            ("afternoon", "Afternoon / Evening (1:00 PM – 12:00 AM)"),
                            ("both", "Full Day (Both Portions)"),
                        ],
                        db_index=True,
                        default="both",
                        max_length=20,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_schedules",
                        to="guest_workspace.collectionline",
                    ),
                ),
            ],
            options={
                "verbose_name": "Line Day Schedule",
                "verbose_name_plural": "Line Day Schedules",
                "ordering": ["day_of_week", "portion"],
            },
        ),
        migrations.AddIndex(
            model_name="collectionline",
            index=models.Index(
                fields=["workspace", "is_active"], name="guest_works_workspa_97659d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="linedayschedule",
            unique_together={("line", "day_of_week")},
        ),
    ]
