# Generated by Django 5.1.15 on 2026-08-08 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0017_collectionline_linedayschedule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="line",
            field=models.ForeignKey(
                blank=True,
                help_text="The collection route/line this customer belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="guest_workspace.collectionline",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="portion",
            field=models.CharField(
                choices=[
                    ("morning", "Morning (1:00 AM – 1:00 PM)"),
                    ("afternoon", "Afternoon / Evening (1:00 PM – 12:00 AM)"),
                    ("both", "Full Day (Both Portions)"),
                ],
                db_index=True,
                default="both",
                help_text="Assigned day portion (Morning 1am-1pm / Afternoon 1pm-12am / Both).",
                max_length=20,
            ),
        ),
    ]
