# Generated by Django 5.1.15 on 2026-08-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guest_workspace", "0018_customerprofile_line_customerprofile_portion"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestworkspace",
            name="subscription_end_date",
            field=models.DateField(
                blank=True,
                help_text="Expiry / end date of current paid subscription membership for this user workspace.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="guestworkspace",
            name="subscription_start_date",
            field=models.DateField(
                blank=True,
                help_text="Start date of current paid subscription membership for this user workspace.",
                null=True,
            ),
        ),
    ]
