# Generated by Django on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlanConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan_code",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "annual_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("max_customers", models.IntegerField(default=50)),
                ("max_collection_days", models.IntegerField(default=7)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_popular", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Subscription Plan Configuration",
                "verbose_name_plural": "Subscription Plan Configurations",
                "ordering": ["sort_order", "monthly_price"],
            },
        ),
    ]
