# Generated by Django 5.1.15 on 2026-07-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_subscriptionplanconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplanconfig",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Timestamp when this record was created."
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplanconfig",
            name="max_customers",
            field=models.IntegerField(default=50, help_text="0 for unlimited"),
        ),
        migrations.AlterField(
            model_name="subscriptionplanconfig",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when this record was last modified."
            ),
        ),
    ]
