# Generated by Django 5.1.15 on 2026-07-27 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_alter_subscriptionplanconfig_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocoupon",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="promocoupon",
            name="valid_from",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="promocoupon",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
