# Generated by Django 5.1.15 on 2026-07-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_alter_promocoupon_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplanconfig",
            name="additional_days",
            field=models.IntegerField(
                default=1,
                help_text="Additional collection days granted by this plan (e.g. 1 for +1 day, 2 for +2 days).",
            ),
        ),
    ]
