# Generated by Django 5.1.15 on 2026-07-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_subscriptionplanconfig_additional_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplanconfig",
            name="target_user_type",
            field=models.CharField(
                choices=[
                    ("guest", "Guest User (Collection Day Add-ons)"),
                    ("lender", "Full ERP Lender (Institutional / Company)"),
                ],
                db_index=True,
                default="guest",
                help_text="Target category: guest (day-based add-ons) or lender (full institutional ERP).",
                max_length=20,
            ),
        ),
    ]
